# Автоматически сгенерированный пайплайн
# Язык: python
# Репозиторий: https://github.com/user/repo.git
# Ветка: develop
# Требования: RAM >= 512MB, Disk >= 2000MB, Port: 8080

stages:
  - build
  - test
  - deploy

variables:
  APP_LANG: "python"
  REQUIRED_MEMORY_MB: "512"
  REQUIRED_DISK_MB: "2000"
  EXPOSED_PORT: "8080"
  REPO_URL: "https://github.com/user/repo.git"
  TARGET_BRANCH: "develop"

build_application:
  stage: build
  image: ubuntu:22.04
  before_script:
    - apt-get update && apt-get install -y git wget sudo
    - git clone --branch "${TARGET_BRANCH}" "${REPO_URL}" /app
    - cd /app

      - apt-get update
      - apt-get install -y python3 python3-pip
      - pip3 install -r requirements.txt
      - python3 -m pytest tests/ || echo "Тесты не обязательны"


  script:
    - echo "Сборка завершена успешно."

  tags:
    - high-mem-512mb
    - disk-2000mb

test_application:
  stage: test
  image: ubuntu:22.04
  script:
    - echo "Запуск тестов..."
    # Тесты могут быть добавлены вручную на основе проекта
    - exit 0  # Заглушка
  needs: ["build_application"]
  rules:
    - if: \$CI_COMMIT_BRANCH == \$TARGET_BRANCH

deploy_staging:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Доставка приложения в staging..."
    - echo "Порт: \$"
    # Здесь может быть rsync, kubectl, scp и т.д.
  environment: staging
  needs: ["test_application"]
  when: manual
  rules:
    - if: \$CI_COMMIT_BRANCH == \$TARGET_BRANCH
